import React from "react";
import { Experience } from "@/types/experience";
import { 
  FaWordpress, FaHtml5, FaCss3Alt, 
  FaNetworkWired, FaPhoneAlt, FaServer, FaDesktop, FaHeadset,
  FaReact, FaSass, FaDocker, FaGitAlt, FaFigma 
} from 'react-icons/fa';
import { SiTypescript, SiTailwindcss, SiJavascript, SiPhp, SiMysql, SiBootstrap, SiDrupal, SiJira, SiAdobexd, SiAdobephotoshop, SiPostgresql, SiSvelte, SiBlazor, SiSlack, SiElementor, SiCodeigniter, SiAdobeillustrator, SiAdobeindesign, SiJquery, SiWoo, SiDotnet, SiChartdotjs, SiSubversion, SiClickup, SiHubspot, SiCisco, SiMicrosoft, SiMicrosoftoutlook, SiWindowsxp, SiKdenlive, SiAdobe, SiOracle } from 'react-icons/si';
import { BsPrinterFill, BsRouter } from 'react-icons/bs';
import { MdPlayLesson } from "react-icons/md";
import { ImOnedrive } from "react-icons/im";
import { DiVisualstudio } from "react-icons/di";

const experiences: Experience[] = [
  {
    id: 'internship',
    title: "Web Designing/Development",
    company: "DMS Services",
    companyShort: "",
    companyDesc: "",
    startDate: '2017-11-04',
    endDate: '2018-02-28',
    location: "Verna, Goa, India",
    link: "",
    favicon: "",
    technologies: [
      React.createElement(SiAdobephotoshop, { size: 20, title: "Photoshop", key: "photoshop" }),
      React.createElement(SiAdobeillustrator, { size: 20, title: "Adobe Illustrator", key: "illustrator" }),
      React.createElement(FaHtml5, { size: 20, title: "HTML5", key: "html5" }),
      React.createElement(FaCss3Alt, { size: 20, title: "CSS3", key: "css3" }),
      React.createElement(SiJavascript, { size: 20, title: "JavaScript", key: "javascript" }),
    ],
  },
  {
    id: 'graduation-project',
    title: "Fleet Management System",
    company: "Padre Conceicao College Of Engineering",
    companyShort: "Goa University",
    companyDesc: "Collaborated with a team of 5 to develop a Fleet Management System as part of our final-year graduation project. The system was designed to track vehicles in real-time using data retrieved from OBD-II (On-Board Diagnostics) adapters. These adapters collected vehicle location and diagnostic information, which was processed and displayed via a full-stack application.",
    startDate: '2017-06-04',
    endDate: '2018-05-28',
    location: "Verna, Goa, India",
    link: "",
    favicon: "",
    technologies: [
      React.createElement(FaHtml5, { size: 20, title: "HTML5", key: "html5" }),
      React.createElement(FaCss3Alt, { size: 20, title: "CSS3", key: "css3" }),
      React.createElement(SiJavascript, { size: 20, title: "JavaScript", key: "javascript" }),
      React.createElement(SiOracle, { size: 20, title: "Oracle Database", key: "oracle-database" }),
      React.createElement(DiVisualstudio, { size: 20, title: "Visual studio", key: "visual-studio" }),
      React.createElement(FaGitAlt, { size: 20, title: "Git", key: "git" })
    ],
  },
  {
    id: 'company1',
    title: "Technical Support Engineer",
    company: "Taj Exotica Resort & Spa",
    companyShort: "Taj Exotica",
    companyDesc: "",
    startDate: '2018-06-04',
    endDate: '2018-12-28',
    location: "Benaulim, Goa, India",
    link: "https://www.tajhotels.com/en-in/hotels/taj-exotica-goa",
    favicon: "https://www.tajhotels.com/favicon.ico",
    technologies: [
      React.createElement(SiCisco, { size: 20, title: "Cisco Network Equipment", key: "cisco" }),
      React.createElement(FaNetworkWired, { size: 20, title: "Network Infrastructure", key: "network-infrastructure" }),
      React.createElement(BsRouter, { size: 20, title: "Router Management", key: "router" }),
      React.createElement(FaServer, { size: 20, title: "Server Management", key: "server" }),
      React.createElement(FaDesktop, { size: 20, title: "Desktop Support", key: "desktop" }),
      React.createElement(BsPrinterFill, { size: 20, title: "Printer Systems", key: "printer" }),
      React.createElement(FaPhoneAlt, { size: 20, title: "PABX Systems", key: "pabx" }),
      React.createElement(FaHeadset, { size: 20, title: "Guest/Technical Support", key: "technical-support" }),
      React.createElement(SiWindowsxp, { size: 20, title: "Windows Systems", key: "windows" }),
      React.createElement(SiMicrosoft, { size: 20, title: "Microsoft Office", key: "microsoft-office" }),
      React.createElement(SiMicrosoftoutlook, { size: 20, title: "Outlook", key: "outlook" })
    ],
  },
  {
    id: 'company2',
    title: "Frontend Web Developer",
    company: "Source it Out",
    companyShort: "Source it Out",
    companyDesc: "",
    startDate: '2019-10-07',
    endDate: '2020-05-29',
    location: "Panjim, Goa, India",
    link: "https://sourceitout.com/",
    favicon: "https://sourceitout.com/wp-content/uploads/2021/03/SIO-web2.png",
    technologies: [
      React.createElement(FaHtml5, { size: 20, title: "HTML5", key: "html5" }),
      React.createElement(FaCss3Alt, { size: 20, title: "CSS3", key: "css3" }),
      React.createElement(SiBootstrap, { size: 20, title: "Bootstrap", key: "bootstrap" }),
      React.createElement(SiJavascript, { size: 20, title: "JavaScript", key: "javascript" }),
      React.createElement(SiChartdotjs, { size: 20, title: "Chart.js", key: "chartjs" }),
      React.createElement(SiDotnet, { size: 20, title: ".NET MVC Framework", key: "dotnet" }),
      React.createElement(FaWordpress, { size: 20, title: "WordPress", key: "wordpress" }),
      React.createElement(SiPhp, { size: 20, title: "PHP", key: "php" }),
      React.createElement(SiHubspot, { size: 20, title: "HubSpot", key: "hubspot" }),
      React.createElement(SiSubversion, { size: 20, title: "SVN", key: "svn" }),
      React.createElement(SiClickup, { size: 20, title: "ClickUp", key: "clickup" })
    ],
  },
  {
    id: 'company3',
    title: "Frontend Developer",
    company: "Invicta eSolutions",
    companyShort: "Invicta eSolutions",
    companyDesc: "",
    startDate: '2020-06-05',
    endDate: '2021-06-30',
    location: "Margao, Goa, India",
    link: "https://invictaindia.in/",
    favicon: "https://invictaindia.in/wp-content/uploads/2020/06/invicta-fav24x16-01.png",
    technologies: [
      React.createElement(FaReact, { size: 20, title: "React", key: "react" }),
      React.createElement(SiJavascript, { size: 20, title: "JavaScript", key: "javascript" }),
      React.createElement(SiJquery, { size: 20, title: "jQuery", key: "jquery" }),
      React.createElement(FaSass, { size: 20, title: "SCSS", key: "scss" }),
      React.createElement(SiBootstrap, { size: 20, title: "Bootstrap", key: "bootstrap" }),
      React.createElement(FaWordpress, { size: 20, title: "WordPress", key: "wordpress" }),
      React.createElement(SiElementor, { size: 20, title: "Elementor", key: "elementor" }),
      React.createElement(SiPhp, { size: 20, title: "PHP", key: "php" }),
      React.createElement(SiCodeigniter, { size: 20, title: "CodeIgniter", key: "codeigniter" }),
      React.createElement(SiMysql, { size: 20, title: "MySQL", key: "mysql" }),
      React.createElement(SiWoo, { size: 20, title: "WooCommerce", key: "woocommerce" }),
      React.createElement(SiAdobexd, { size: 20, title: "Adobe XD", key: "adobexd" }),
      React.createElement(SiAdobephotoshop, { size: 20, title: "Photoshop", key: "photoshop" }),
      React.createElement(SiAdobeillustrator, { size: 20, title: "Adobe Illustrator", key: "illustrator" }),
      React.createElement(SiAdobeindesign, { size: 20, title: "Adobe InDesign", key: "indesign" }),
      React.createElement(FaGitAlt, { size: 20, title: "Git", key: "git" }),
      React.createElement(SiSlack, { size: 20, title: "Slack", key: "slack" })
    ],
  },
  {
    id: 'company4',
    title: "Software Developer",
    company: "Creative Capsule",
    companyShort: "Creative Capsule",
    companyDesc: "Specialized in creating dynamic, user-friendly web interfaces and optimizing performance for Drupal-based solutions. Led projects that enhanced user engagement and accessibility by 30%.",
    startDate: '2021-07-15',
    endDate: '2024-09-30',
    location: "Verna, Goa, India",
    link: "http://creativecapsule.com",
    favicon: "https://www.creativecapsule.com/wp-content/themes/creative-capsule/content/images/content-images/apple-touch-icon.png",
    technologies: [
      React.createElement(FaReact, { size: 20, title: "React", key: "react" }),
      React.createElement(SiSvelte, { size: 20, title: "Svelte", key: "svelte" }),
      React.createElement(SiBlazor, { size: 20, title: "Blazor", key: "blazor" }),
      React.createElement(SiTypescript, { size: 20, title: "TypeScript", key: "typescript" }),
      React.createElement(FaSass, { size: 20, title: "SCSS", key: "sass" }),
      React.createElement(SiTailwindcss, { size: 20, title: "Tailwind CSS", key: "tailwind" }),
      React.createElement(SiBootstrap, { size: 20, title: "Bootstrap 5", key: "bootstrap" }),
      React.createElement(SiDrupal, { size: 20, title: "Drupal", key: "drupal" }),
      React.createElement(FaWordpress, { size: 20, title: "WordPress", key: "wordpress" }),
      React.createElement(SiElementor, { size: 20, title: "Elementor", key: "elementor" }),
      React.createElement(SiPostgresql, { size: 20, title: "PostgreSQL", key: "postgresql" }),
      React.createElement(FaFigma, { size: 20, title: "Figma", key: "figma" }),
      React.createElement(SiAdobexd, { size: 20, title: "Adobe XD", key: "adobexd" }),
      React.createElement(SiAdobephotoshop, { size: 20, title: "Photoshop", key: "photoshop" }),
      React.createElement(FaDocker, { size: 20, title: "Docker", key: "docker" }),
      React.createElement(FaGitAlt, { size: 20, title: "Git", key: "git" }),
      React.createElement(SiJira, { size: 20, title: "Jira", key: "jira" })
    ],
  },
  {
    id: 'company5',
    title: "EPR Training Collateral Developer",
    company: "BHRUT NHS Trust",
    companyShort: "BHRUT NHS Trust",
    companyDesc: "Collaborated with healthcare professionals to design, develop, and manage training documentation for NHS systems, contributing to improved digital adoption across departments.",
    startDate: '2025-01-13',
    endDate: '',
    location: "Romford, United Kingdom",
    link: "https://www.bhrhospitals.nhs.uk/",
    favicon: "",
    technologies: [
      React.createElement(SiMicrosoft, { size: 20, title: "Microsoft Office 365", key: "microsoft-office-365" }),
      React.createElement(ImOnedrive, { size: 20, title: "SharePoint", key: "sharepoint" }),
      React.createElement(SiKdenlive, { size: 20, title: "Kdenlive Video Editing", key: "kdenlive" }),
      React.createElement(MdPlayLesson, { size: 20, title: "Articulate 360", key: "articulate-360" }),
      React.createElement(SiAdobe, { size: 20, title: "Adobe Premiere Pro", key: "adobe-premiere" }),
      React.createElement(SiOracle, { size: 20, title: "Oracle Millennium Cerner Software", key: "oracle-millennium" })
    ],
  },
];

export default experiences;